project:
  type: website

website:
  title: "POPPK in {admiral}"
  navbar:
    pinned: true
    collapse: false
    background: primary
    search: true
    right:
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/jeffreyad/adppk
        aria-label: Repository      
  sidebar:
    - id: sidebar
      style: docked
      collapse-level: 1
      logo: images/pharmaverse.png
      border: true
      contents:
      - adppk.qmd
      - PK_programming_pharmaverse.qmd
      - phuse_poster.qmd
      - phuse_poster_pptx.qmd

  favicon: images/pharmaverse-favicon.png
  

format:
  html:
    theme:
      light:
        - flatly
      dark:
        - darkly
    css: styles.css
    toc: true

editor: visual

